apiVersion: apps/v1
kind: Deployment
metadata:
  name: byeol-py-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byeol-py
  template:
    metadata:
      labels:
        app: byeol-py
    spec:
      serviceAccountName: eks-secret-manager
      volumes:
      - name: secrets-store
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "eks-secret-provider" 
      containers:
        - name: byeol-py-con
          image: 655088038759.dkr.ecr.ap-northeast-2.amazonaws.com/byeol-redispy:16
          envFrom:
          - secretRef:
              name: eks-secret
          volumeMounts:
          - name: secrets-store
            mountPath: "/mnt/secrets-store"
            readOnly: true
---
apiVersion: v1
kind: Service
metadata:
  name: test-py-svc
spec:
  type: ClusterIP
  selector:
    app: byeol-py
  ports:
    - port: 5000
      targetPort: 5000
